### PR TITLE
editing saledate vars

### PR DESCRIPTION
**Pull request by eburton9**
@ptatian I tried a couple different things to see why my code isn't working correctly but I'm unable to identify any issues so sending your way for help. Thank you.

### CODE REVIEW

**Comment by ptatian** [comment]
This syntax doesn't work with IF. 
`if all_saledate < '01Jan2006'd or > '31mar2023'd then delete;`

You need to use this:
`if all_saledate < '01Jan2006'd or all_saledate > '31mar2023'd then delete;`

Or, alternatively, you can use:
`if '01Jan2006'd <= all_saledate <= '31mar2023'd;`

IF without a THEN keeps only those observations that satisfy the condition.

**Comment by ptatian** [comment]
Thanks, @eburton9 Does the revised code seem to be adding sales that we need for the notices I flagged in issue #375?

**Comment by eburton9** [comment]
@ptatian It looks like for ID 232 and ID 316 there are dates from owernpt_extractdat_first when saledate was blank. ID 894 isn't coming up in this recently created dataset or the one before it.. I know the other ids are other issues but I printed them anyways. For 989 and 990 the ownerpt_extractdat_first is actually after the saledate. 10004 and 10005 do seem duplicated.

**Comment by ptatian** [comment]
Thanks, @eburton9 Good that 232 and 316 now have sales showing up. 894 was a different problem. As was 989 and 990. And the duplicate. For these, we need to make changes to TOPA_data_to_DC_data.sas. I will make a new issue for that and tag you. We will need to complete the new issue and then return to this one.

**Comment by eburton9** [comment]
@ptatian Updated based on [Issue 377](https://github.com/NeighborhoodInfoDC/PresCat/issues/377)

**Comment by ptatian** [comment]
@eburton9 For your awareness, I've updated the Topa_addresses data set to remove non-exact adress matches. We were previously matching to some other address than the one listed, which is not what we want. This should result in these notices being dropped from the analysis.

   ID  | All street addresses       
-- | --
   25 | 4837 3rd Street NE         
   41 | 1302 12th Street NW        
  127 | 4209 Dix Street NW         
  176 | 4837 3rd Street NE         
  223 | 4912 Nash Street NW        
  309 | 1011 7th Street NW         
  471 | 2020 19th Street SE        
  617 | 1911 18th Street NW        
  812 | 501 12th Street SE         
 1016 | 4619 Nash Street NE        
 1381 | 4725 Foote Street NE       
10006 | 86 Webster Street NW       
10009 | 624 Girard Street Northwest

**Comment by ptatian** [comment]
Hi @eburton9 I think that we may be done with this issue. If you would just check things run properly after the other data sets were updated, then I think we can finalize this one. We'll have to make some other changes based on the CBO review, but I'd like to finalize this first and go back to those. 

One small change is we should add a LABEL statement to the Proc Summary at line 33 to label the new u_sum_units variable. Currently, it's inheriting the label from Topa_addresses, but this label is a little misleading/confusing because it refers to individual buildings, where u_sum_units is the total of units across all buildings associated with the notice. I think a new label like, "Sum of MAR units for all associated buildings (Urban created var)" would be better. Thanks!

**Comment by eburton9** [comment]
@ptatian updated label and there were zero obs when trying to print those IDs. I'm assuming that means the data update worked. I'll merge, sync, batch submit.

**Pull request merged**
