### PR TITLE
Update Pres_cat_web_export.sas

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui Hi Mychal. The HUD data hasn't updated yet for the January prescat update so I went ahead and started to update the website and ran into an issue similar to last time. I updated the code for it, please review.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 Hey Will. Can you remind me of the issue?

**Comment by Woliver01** [comment]
@mcohenui When I tried to update the REAC file, I got an error message saying that a few of the properties weren't able to upload. Last time the issue was with the Real Property Event dates, but this time it's the REAC score dates. I believe that the issue last time was that the earlier missing dates just weren't coded as anything and so Peter decided it would be best to just code them as 1/1/1900.

**Comment by mcohenui** [comment]
@Woliver01 Thanks for the refresh. The program is good to merge. You mentioned there were no HUD updates, were there DHCD RCASD updates?

**Comment by Woliver01** [comment]
@mcohenui Yes, there are four new ones. Should I just move on to that part of the update?

**Comment by mcohenui** [comment]
@Woliver01 Yep, just wanted to check if there were additional DHCD updates.

**Pull request merged**
