### PR TITLE
Update TOPA_data_to_DC_data.sas

### PR DESCRIPTION
**Pull request by eburton9**
For https://github.com/NeighborhoodInfoDC/PresCat/issues/328 The spreadsheet for no sale after 365 days looks correct after your suggestions, @ptatian. The spreadsheet is :https://urbanorg.box.com/s/7cpd0yjkrbz6q9ukhg5bw0dihvs3b28x

### CODE REVIEW

**Comment by ptatian** [comment]
Thanks @eburton9! Address2 is almost always blank, so I think we can drop it. But would you please add the owner name for the sale?

**Comment by eburton9** [comment]
@ptatian code and [spreadsheet ](https://urbanorg.box.com/s/7cpd0yjkrbz6q9ukhg5bw0dihvs3b28x)in Box updated.

**Comment by ptatian** [comment]
Thanks, @eburton9. I've shared with CNHED, cc'ing you. Let's hold on finalizing until we see their reaction.

**Comment by eburton9** [comment]
@ptatian Tagging you in this old pull request because it has conflicts now.. This was likely my fault for not knowing this pull request existed when I just updated the TOPA_data_to_DC_data prog for the spreadsheet update..

**Comment by ptatian** [comment]
@eburton9 Let me take a look.

**Comment by ptatian** [comment]
@eburton9 It's fine now.

**Pull request merged**
