### PR TITLE
Enhancement #21

### PR DESCRIPTION
**Pull request by mcohenui**
@ptatian Please review series of macros to update Reac_score file with new REAC scores. There are a number of DC REAC scores that are not attached to NLIHC IDs. Not sure how to handle those.

### CODE REVIEW

**Comment by ptatian** [comment]
@mcohenui Sorry for the delay in getting to this. I will review.

**Comment by ptatian** [comment]
Hi @mcohenui. Do you think we can wrap this up this week? Thanks.

**Comment by mcohenui** [comment]
@ptatian I added most of the unmatched ids to the $reac_nlihcid format. There were two that did not seem to be in the catalog. Should be ready for final review.

**Comment by ptatian** [comment]
Thank you, @mcohenui. I'll take a look.

**Comment by ptatian** [comment]
Hi @mcohenui. This all looks good! You can go ahead and merge the pull request, sync the changes to L:, batch submit on L:, and then close the original issue. 

We should follow up with the Preservation Network on the two projects we couldn't match to see if anyone knows what they are and whether we should add them to the Catalog. 

Thanks!

**Pull request merged**
