### PR TITLE
Create Update_Sec8mf_2019_04.sas

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui The code that makes the PDFs seems to be hardcoded to the D: drive. Are there any workarounds for this? cc: @ptatian

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 This will be a bit hard to troubleshoot, since I am not sure how to reproduce the D drive issue. What errors are you seeing? cc: @ptatian

**Comment by Woliver01** [comment]
@mcohenui cc: @ptatian The errors are at the bottom, the top is just context:

MPRINT(UPDATE_SEC8MF_SUBSIDY):   ods proclabel "New subsidy records";
MPRINT(UPDATE_SEC8MF_SUBSIDY):   proc report data=Subsidy_target_update_b nowd;
MPRINT(UPDATE_SEC8MF_SUBSIDY):   where not In_Subsidy_target and not( missing( nlihc_id ) );
MPRINT(UPDATE_SEC8MF_SUBSIDY):   column nlihc_id Subsidy_id Subsidy_Info_Source_ID Units_Assist POA_start POA_end Compl_end
POA_end_actual Subsidy_Active Program Rent_to_FMR_description;
MPRINT(UPDATE_SEC8MF_SUBSIDY):   define nlihc_id / order noprint;
MPRINT(UPDATE_SEC8MF_SUBSIDY):   define Subsidy_id / display "Subsidy ID" style=[textalign=center];
MPRINT(UPDATE_SEC8MF_SUBSIDY):   define Subsidy_Info_Source_ID / display "Project ID" style=[textalign=center];
MPRINT(UPDATE_SEC8MF_SUBSIDY):   break before nlihc_id / ;
MPRINT(UPDATE_SEC8MF_SUBSIDY):   compute before nlihc_id / style=[textalign=left fontweight=bold];
MPRINT(UPDATE_SEC8MF_SUBSIDY):   line nlihc_id $nlihcid_proj.;
MPRINT(UPDATE_SEC8MF_SUBSIDY):   endcomp;
MPRINT(UPDATE_SEC8MF_SUBSIDY):   title3 "PresCat.Subsidy - New subsidy records from Sec8mf_2019_04 (added to Catalog)";
MPRINT(UPDATE_SEC8MF_SUBSIDY):   run;
NOTE: No observations were selected from data set WORK.SUBSIDY_TARGET_UPDATE_B.
NOTE: No observations in input data set.
NOTE: There were 0 observations read from the data set WORK.SUBSIDY_TARGET_UPDATE_B.
      WHERE (not In_Subsidy_target) and (not MISSING(nlihc_id));
NOTE: PROCEDURE REPORT used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


MPRINT(UPDATE_SEC8MF_SUBSIDY):   ods pdf close;
**ERROR: Physical file does not exist, D:\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2019_04_subsidy.pdf.**
MPRINT(UPDATE_SEC8MF_SUBSIDY):   ods tagsets.excelxp
file="D:\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2019_04_subsidy_nonmatch.xls" style=Minimal
options(sheet_interval='Proc' );
NOTE: Writing TAGSETS.EXCELXP Body file: D:\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2019_04_subsidy_nonmatch.xls
**ERROR: Physical file does not exist, D:\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2019_04_subsidy_nonmatch.xls.
ERROR: No body file. TAGSETS.EXCELXP output will not be created.**

**Comment by rpitingolo** [comment]
@Woliver01 @mcohenui I think this will resolve once we do the Autoexec.sas fix I just posted about. Wil - I will come down to you in a few min.

**Comment by ptatian** [comment]
@Woliver01 @rpitingolo Did that fix the problem?

**Comment by rpitingolo** [comment]
@ptatian yes, @Woliver01 was able to export the PDFs once we made the fix.

**Comment by Woliver01** [comment]
@mcohenui There was a note on an invalid argument but no errors. I tried looking for the macros but couldn't locate it. Please review.

**Comment by mcohenui** [comment]
@Woliver01 you should be good to try the REAC program again

**Comment by Woliver01** [comment]
@mcohenui I got these notes this time:

NOTE: Invalid third argument to function SUBSTR at line 7 column 71.
NOTE: Invalid second argument to function SUBSTR at line 7 column 135.
property_name=Victory Heights state_name=DISTRICT OF COL city=WASHINGTON state_code=DC rems_property_id=800218062
inspec_id_1=555016 inspec_score_1=100a release_date_1=10/29/2015 inspec_id_2=355302 inspec_score_2=99b
release_date_2=3/17/2011 inspec_id_3=  inspec_score_3=  release_date_3=  REAC_date=. REAC_score=  REAC_score_num=.
REAC_score_letter=  REAC_score_star=  REAC_ID=800218062 nlihc_id=  num=4 date=  j=0 _ERROR_=1 _N_=109
NOTE: Invalid third argument to function SUBSTR at line 7 column 71.
NOTE: Invalid second argument to function SUBSTR at line 7 column 135.
NOTE: Invalid third argument to function SUBSTR at line 7 column 71.
NOTE: Invalid second argument to function SUBSTR at line 7 column 135.
property_name=CHAPIN STREET APTS state_name=DISTRICT OF COL city=WASHINGTON state_code=DC rems_property_id=800218204
inspec_id_1=623974 inspec_score_1=64c release_date_1=3/30/2018 inspec_id_2=  inspec_score_2=  release_date_2=  inspec_id_3=
inspec_score_3=  release_date_3=  REAC_date=. REAC_score=  REAC_score_num=. REAC_score_letter=  REAC_score_star=
REAC_ID=800218204 nlihc_id=  num=4 date=  j=0 _ERROR_=1 _N_=111

**Comment by mcohenui** [comment]
@Woliver01 So, I am pretty sure the issue is that there has only been one inspection for those buildings. So the second and third inspection fields are blank. Which would cause the invalid data note. Can you cross check these buildings with the raw data (or with the HUD file, whichever is easier) to confirm?

If so, then the program is fine to move forward, though we should maybe think about a more elegant way to handle buildings that have only had one REAC inspection in the future.

**Comment by Woliver01** [comment]
@mcohenui Thanks Mychal. That was the case. I'll merge and finish the update tomorrow.

**Comment by ptatian** [comment]
Thanks @Woliver01 and @mcohenui. Mychal, perhaps you can create a new issue about the single inspection issue, so that we don't forget about it.

**Pull request merged**
