### PR TITLE
Updated MFIS catalog data for February catalog

### PR DESCRIPTION
**Pull request by katyaabaz**
MFIS data from 01 2016

### CODE REVIEW

**Comment by katyaabaz** [comment]
@NeighborhoodInfoDC/review MFIS catalog update needs review.

**Comment by ptatian** [comment]
@katyaabaz Reviewing now.

**Comment by ptatian** [comment]
@katyaabaz You forgot to put your name and date in the program header. I'll let you do it this time. Then you can commit the change and merge the pull request.

**Comment by katyaabaz** [comment]
@ptatian done, thank you!

**Pull request merged**
