### PR TITLE
Update Pres Cat with HUD data May 2019

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui I got a few errors like this:
ERROR: Physical file does not exist,
       D:\DCData\Libraries\PresCat\Prog\Updates\Update_Sec8mf_2019_05_project.pdf.

The program is still trying to pull from the D:Drive, not sure why. Please review.

### CODE REVIEW

**Comment by Woliver01** [comment]
Hi @ptatian , the program is trying to pull from the D: Drive (see error message above) even after @rpitingolo and I added the Autoexec.sas solution. The last update worked fine so I'm not sure what changed.

**Comment by rpitingolo** [comment]
@Woliver01 did you figure it out? Let me know if I should come down to look.

**Comment by Woliver01** [comment]
@rpitingolo If you could come down and look that'd be helpful. Thanks.

**Comment by rpitingolo** [comment]
@Woliver01 were you able to get it to run successfully?

**Comment by Woliver01** [comment]
@rpitingolo I got everything straightened out. The program produced the pdfs. 
@mcohenui Some of the pdfs have "unknown" values. I'll send you a separate email with the PDFs attached, and the log looks fine but please review just in case.

**Comment by rpitingolo** [comment]
Thanks @Woliver01 

@ptatian it seems that when they upgraded Will to the new version of SAS it reset his config file. Something to keep in mind when upgrades happen.

**Comment by mcohenui** [comment]
@Woliver01 good to merge

**Pull request merged**
