### PR TITLE
Update #345

### PR DESCRIPTION
**Pull request by dharvey17**
Ready for your to look @ptatian

### CODE REVIEW

**Comment by ptatian** [comment]
Hi @dharvey17 I figured out that the SET statement with OBS=0 was the problem. So I just took that out. The only thing that adds is that we should declare lengths of any character variables first using a LENGTH statement. I added a couple of examples and am asking you to fill in the remaining ones. 

Also, `= 4/8/2022` is not the correct way to specify a date value in SAS. (It actually just divides 4 by 8 by 2022.) The two options are: 
- Use the mdy() function: `= mdy( 4, 8, 2022 )`
- Use a SAS literal date value: `= '8apr2022'd`

**Comment by ptatian** [comment]
On Cedar Heights, maybe I got confused by all the name changes, etc. It seems like the contract that was in the 2020 update is already in Prescat.Subsidy, so there really isn't anything to add. We can skip that step.

**Comment by ptatian** [comment]
But we still want to do the project rename from Finsbury Square Apts to Cedar Heights.

**Comment by dharvey17** [comment]
@ptatian ready for review.

**Comment by ptatian** [comment]
Hi @dharvey17 For your awareness, I am reviewing this, but found a problem with one of the previous updates that I'm investigating further. Hope to get back to you shortly. Thank you for your patience.

**Review by ptatian — APPROVED** [review]
@dharvey17 This is good to go. I had to fix some things with variable names that might have been my fault. I also seemed to have still been confused about Augusta Louisa, but got it sorted out. Felt it was easier to just make those corrections directly. I added a couple of Proc Compare's, which I sometimes use to make sure that changes I'm introducing to files are only what I expect. 

You can go ahead and finalize this. Thanks!

**Pull request merged**
