### PR TITLE
Update #244

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui In response to your email, yes I'm getting an error about the date being after the most recent update. Please review.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 So taking a look at it, the program should run fine if you change the file name in program to the July file. And then it will run with the updated July file.

**Comment by mcohenui** [comment]
@Woliver01 Just checking in on whether my last comment alleviated the issue or if you have any additional questions.

**Comment by Woliver01** [comment]
@mcohenui Hey Mychal, I was wrapping up another deliverable. I'm not sure that I understand what you mean. Do you mean I should name it MFIS_2020_07 and not ....._08?

**Comment by mcohenui** [comment]
@Woliver01 No worries. I mean editing the call "%Update_MFIS( Update_file=MFIS_2020_08 )" to call in the MFIS_2020_07 file (which has now been updated with the 7.31 data).

**Comment by Woliver01** [comment]
@mcohenui Gotcha, will do.

**Comment by Woliver01** [comment]
@mcohenui Should I do the same for the REAC file?

**Comment by mcohenui** [comment]
@Woliver01 Was there the same issue in the HUD repository with the REAC program?

**Comment by Woliver01** [comment]
@mcohenui Yes, this one was also 7/31 while the prior update date was 7/01/2020.

**Comment by mcohenui** [comment]
@Woliver01 I actually only see programs in the HUD folder for July (REAC_2020_07) and June (REAC_2020_06) for REAC. I don't actually see an REAC_2020_08 program. Am I just missing it?

**Comment by Woliver01** [comment]
@mcohenui My mistake, you are correct. Also here's the REAC program as well.

**Comment by mcohenui** [comment]
@Woliver01 good to merge

**Pull request merged**
