### PR TITLE
Create New_projects_issue_300.sas

### PR DESCRIPTION
**Pull request by dharvey17**
Flagging for review @ptatian 

Duplicate addresses for Marian House and Fendall Heights; Park 7 Apartments

### CODE REVIEW

**Comment by ptatian** [comment]
Thank you, @dharvey17. I will take a look.

**Comment by ptatian** [comment]
Hi @dharvey17. Sorry for the delay in getting back to you on this. After looking more closely, I realized it was confusing the way we had the geocoding and input data set up. So, as we talked about, I changed the code so that it no longer uses the MAR app. The gecoding is now done entirely in the SAS program; no separate process is required. These changes have been merged into this branch from main, so you should pull the latest version of the branch to your desktop before continuing. 

In the new system, we have just two input files, which I've called **New_projects_issue_300_rev.csv** and **New_projects_issue_300_rev_subsidy.csv**. An ID column links the rows in the two sheets together. I used the address IDs, since we had those already, with some changes discussed below, but in the future we can use any unique numbering to link projects and subsidies.

In reviewing the data I realized that there were not only duplicates between the new LIHTC data and the Catalog projects, but also within the new LIHTC data we had multiple tax credit allocations for the same project. For example, Marian House and Scattered Site II/Marian House both had the same address, so these are a single project with two separate tax credit allocations. But, in addition, the property data revealed that Fendall Heights is owned by the same entity so, in fact, these are all one project. In the input data, I deleted the extra project rows and edited the name so now there is just one entry for this project:

ID | Proj_name
-- | --
52616 | Fendall Heights/Marian House/Scattered Site   II

With four subsidy records:

ID | Units_tot | Subsidy_Info_Source_ID | Subsidy_Info_Source
-- | -- | -- | --
52616 | 42 | DCB00000010 | HUD/Low Income Housing Tax Credits
52616 | 27 | DCB00000005 | HUD/Low Income Housing Tax Credits
52616 | 42 | DCB20141005 | HUD/Low Income Housing Tax Credits
52616 | 28 | DCB20132001 | HUD/Low Income Housing Tax Credits

I picked one of the address IDs to use as a reference. It didn't matter which because it's only a way of linking the project and subsidy data. 

Similarly, Milestones at 2nd Street and Milestones at Piney Branch had separate addresses and tax credit allocations, but are actually owned by the same entity. So I also considered these to be one project. And Park 7 and Park 7 Apartments in the input data had the same address and are now treated as a single project. 

***

For **NEXT STEPS** to finish this issue, please pull all the new code to your local branch. When you submit the program, you will see that we still have a duplicates listed for Portner Flats (Portner Place), as well as Augusta Louisa and the new Fendall Heights/etc. project. We already decided that we will add Fendall Heights/etc. as a new project to the Catalog, so we don't need to change anything there. 

For Portner Flats, this is already a Catalog project (NL000243), so you should **remove the project and subsidy records for this project (ID=298461)** from  **New_projects_issue_300_rev.csv** and **New_projects_issue_300_rev_subsidy.csv**. But you should save the information elsewhere as we will need to add the new subsidies to Portner Flats in a separate issue. 

Once you have done the above, please tag me on this pull request and I will review again. Thanks!

**Comment by ptatian** [comment]
Donovan, for your awareness, I edited my previous comment above because, as I was reviewing things, I realized that three projects that are all owned by Scattered Site II Llc was causing the confusion in the address and SSL data. The code we have looks for identical owner names and matches up subsidies based on that. In this case, however, the projects are geographically distinct and it's better to treat them as three separate projects in the Catalog, even if they are owned by the same entity. I updated the data and code to account for this.

**Comment by dharvey17** [comment]
Hi @ptatian It looks like the only task was removing Portner Place from the rev.csv and subsisdy_rev.csv files. I made the changes in sas1 and created a new file (Portner Flats Information (Issue_335).xlsx) with the now deleted records.

Also, just for my information, why are we treating Milestones at 2nd Street and Milestones at Piney Branch as one project (seperate addresses, one owner) but separating the Scattered Site projects?

**Review by ptatian — APPROVED** [review]
Hi @dharvey17 Looks good! You can go ahead and finalize this one.

**Comment by dharvey17** [comment]
\\sas1\DCDATA\Libraries\PresCat\Prog\AddNew\New_projects_issue_300.lst
\\sas1\DCDATA\Libraries\PresCat\Prog\AddNew\New_projects_issue_300.log

**Pull request merged**
